export const BUFF_PRESETS = [
  {
    id: "bless",
    label: "BOT.presets.bless.label",
    description: "BOT.presets.bless.description",
    flag: {
      targetMode: "target",
      allowMultipleTargets: true,
      fallbackToSelfIfNoTarget: true,
      multiTargetLimit: {
        enabled: true,
        baseTargets: 3,
        baseSpellLevel: 1,
        targetsPerLevelAbove: 1,
      },
      type: "passive",
      rollModifier: {
        enabled: true,
        formula: "1d4",
        rollTypes: ["attack", "save"],
      },
      consumeOnTrigger: false,
    },
  },
  {
    id: "bane",
    label: "BOT.presets.bane.label",
    description: "BOT.presets.bane.description",
    flag: {
      targetMode: "target",
      allowMultipleTargets: true,
      multiTargetLimit: {
        enabled: true,
        baseTargets: 3,
        baseSpellLevel: 1,
        targetsPerLevelAbove: 1,
      },
      type: "passive",
      rollModifier: {
        enabled: true,
        formula: "-1d4",
        rollTypes: ["attack", "save"],
      },
      save: {
        enabled: true,
        timing: "activation",
        ability: "cha",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      consumeOnTrigger: false,
    },
  },
  {
    id: "guidance",
    label: "BOT.presets.guidance.label",
    description: "BOT.presets.guidance.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      rollModifier: {
        enabled: true,
        formula: "1d4",
        rollTypes: ["ability", "skill"],
      },
      charges: 1,
      consumeOnTrigger: false,
    },
  },
  {
    id: "resistance",
    label: "BOT.presets.resistance.label",
    description: "BOT.presets.resistance.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      rollModifier: {
        enabled: true,
        formula: "1d4",
        rollTypes: ["save"],
      },
      charges: 1,
      consumeOnTrigger: false,
    },
  },
  {
    id: "hex",
    label: "BOT.presets.hex.label",
    description: "BOT.presets.hex.description",
    flag: {
      targetMode: "self",
      rememberTargetOnActivation: true,
      requireStoredTargetMatch: true,
      type: "anyAttack",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "necrotic",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
    },
  },
  {
    id: "huntersMark",
    label: "BOT.presets.huntersMark.label",
    description: "BOT.presets.huntersMark.description",
    flag: {
      targetMode: "self",
      rememberTargetOnActivation: true,
      requireStoredTargetMatch: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d6",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
    },
  },
  {
    id: "fireShieldWarm",
    label: "BOT.presets.fireShieldWarm.label",
    description: "BOT.presets.fireShieldWarm.description",
    flag: {
      targetMode: "self",
      type: "damaged",
      receivedAttackType: "melee",
      damage: {
        formula: "2d8",
        type: "fire",
        targetMode: "attacker",
      },
      buffs: {
        resistances: ["cold"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "fireShieldChill",
    label: "BOT.presets.fireShieldChill.label",
    description: "BOT.presets.fireShieldChill.description",
    flag: {
      targetMode: "self",
      type: "damaged",
      receivedAttackType: "melee",
      damage: {
        formula: "2d8",
        type: "cold",
        targetMode: "attacker",
      },
      buffs: {
        resistances: ["fire"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "heroism",
    label: "BOT.presets.heroism.label",
    description: "BOT.presets.heroism.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "turnStart",
      temporaryHp: {
        formula: "@origin.spell.mod",
        targetMode: "self",
        mode: "keepHighest",
      },
      buffs: {
        conditionImmunities: ["frightened"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "armorOfAgathys",
    label: "BOT.presets.armorOfAgathys.label",
    description: "BOT.presets.armorOfAgathys.description",
    flag: {
      targetMode: "self",
      type: "damaged",
      receivedAttackType: "melee",
      requireBearerTemporaryHp: true,
      temporaryHp: {
        formula: "@spellLevel * 5",
        timing: "activation",
        targetMode: "self",
        mode: "keepHighest",
      },
      damage: {
        formula: "@spellLevel * 5",
        type: "cold",
        targetMode: "attacker",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "simpleRegeneration",
    label: "BOT.presets.simpleRegeneration.label",
    description: "BOT.presets.simpleRegeneration.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "turnStart",
      healing: {
        formula: "1d6",
        targetMode: "self",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "divineFavor",
    label: "BOT.presets.divineFavor.label",
    description: "BOT.presets.divineFavor.description",
    flag: {
      targetMode: "self",
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d4",
        type: "radiant",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "wrathfulSmite",
    label: "BOT.presets.wrathfulSmite.label",
    description: "BOT.presets.wrathfulSmite.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "psychic",
        targetMode: "triggerTarget",
      },
      save: {
        enabled: true,
        timing: "trigger",
        ability: "wis",
        dcSource: "origin",
        effect: "full",
      },
      status: {
        id: "frightened",
        ids: ["frightened"],
        targetMode: "triggerTarget",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "shieldOfFaith",
    label: "BOT.presets.shieldOfFaith.label",
    description: "BOT.presets.shieldOfFaith.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        ac: 2,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "brandingSmite",
    label: "BOT.presets.brandingSmite.label",
    description: "BOT.presets.brandingSmite.description",
    flag: {
      targetMode: "self",
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "2d6",
        type: "radiant",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "blindingSmite",
    label: "BOT.presets.blindingSmite.label",
    description: "BOT.presets.blindingSmite.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "3d8",
        type: "radiant",
        targetMode: "triggerTarget",
      },
      save: {
        enabled: true,
        timing: "trigger",
        ability: "con",
        dcSource: "origin",
        effect: "full",
        repeat: {
          enabled: true,
          timing: "endTurn",
          endsBuffOn: "success",
        },
      },
      status: {
        id: "blinded",
        ids: ["blinded"],
        targetMode: "triggerTarget",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "thunderousSmite",
    label: "BOT.presets.thunderousSmite.label",
    description: "BOT.presets.thunderousSmite.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "2d6",
        type: "thunder",
        targetMode: "triggerTarget",
      },
      save: {
        enabled: true,
        timing: "trigger",
        ability: "str",
        dcSource: "origin",
        effect: "full",
      },
      status: {
        id: "prone",
        ids: ["prone"],
        targetMode: "triggerTarget",
        applyCondition: "saveFailure",
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "holyWeapon",
    label: "BOT.presets.holyWeapon.label",
    description: "BOT.presets.holyWeapon.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "2d8",
        type: "radiant",
        targetMode: "triggerTarget",
      },
      reminders: {
        enabled: true,
        message: "BOT.presets.holyWeapon.reminder",
        timing: {
          activation: true,
        },
        visibility: "gm",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "stoneskin",
    label: "BOT.presets.stoneskin.label",
    description: "BOT.presets.stoneskin.description",
    flag: {
      targetMode: "target",
      type: "passive",
      buffs: {
        resistances: ["bludgeoning", "piercing", "slashing"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enlarge",
    label: "BOT.presets.enlarge.label",
    description: "BOT.presets.enlarge.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d4",
        targetMode: "triggerTarget",
      },
      buffs: {
        abilityCheckAdvantages: ["str"],
        savingThrowAdvantages: ["str"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "absorbElementsAcid",
    label: "BOT.presets.absorbElementsAcid.label",
    description: "BOT.presets.absorbElements.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "acid",
        targetMode: "triggerTarget",
      },
      buffs: {
        resistances: ["acid"],
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "absorbElementsCold",
    label: "BOT.presets.absorbElementsCold.label",
    description: "BOT.presets.absorbElements.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "cold",
        targetMode: "triggerTarget",
      },
      buffs: {
        resistances: ["cold"],
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "absorbElementsFire",
    label: "BOT.presets.absorbElementsFire.label",
    description: "BOT.presets.absorbElements.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "fire",
        targetMode: "triggerTarget",
      },
      buffs: {
        resistances: ["fire"],
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "absorbElementsLightning",
    label: "BOT.presets.absorbElementsLightning.label",
    description: "BOT.presets.absorbElements.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "lightning",
        targetMode: "triggerTarget",
      },
      buffs: {
        resistances: ["lightning"],
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "absorbElementsThunder",
    label: "BOT.presets.absorbElementsThunder.label",
    description: "BOT.presets.absorbElements.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "thunder",
        targetMode: "triggerTarget",
      },
      buffs: {
        resistances: ["thunder"],
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "haste",
    label: "BOT.presets.haste.label",
    description: "BOT.presets.haste.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        ac: 2,
        savingThrowAdvantages: ["dex"],
        movement: { enabled: true, mode: "multiply", value: "2", types: ["all"] },
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "longstrider",
    label: "BOT.presets.longstrider.label",
    description: "BOT.presets.longstrider.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        movement: { enabled: true, mode: "add", value: "+10", valueFeet: 10, types: ["walk"] },
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "falseLife",
    label: "BOT.presets.falseLife.label",
    description: "BOT.presets.falseLife.description",
    flag: {
      targetMode: "self",
      type: "passive",
      temporaryHp: {
        formula: "1d4 + 4 + ((@spellLevel - 1) * 5)",
        timing: "activation",
        targetMode: "self",
        mode: "keepHighest",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEnergyAcid",
    label: "BOT.presets.protectionFromEnergyAcid.label",
    description: "BOT.presets.protectionFromEnergy.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["acid"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEnergyCold",
    label: "BOT.presets.protectionFromEnergyCold.label",
    description: "BOT.presets.protectionFromEnergy.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["cold"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEnergyFire",
    label: "BOT.presets.protectionFromEnergyFire.label",
    description: "BOT.presets.protectionFromEnergy.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["fire"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEnergyLightning",
    label: "BOT.presets.protectionFromEnergyLightning.label",
    description: "BOT.presets.protectionFromEnergy.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["lightning"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEnergyThunder",
    label: "BOT.presets.protectionFromEnergyThunder.label",
    description: "BOT.presets.protectionFromEnergy.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["thunder"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityBullsStrength",
    label: "BOT.presets.enhanceAbilityBullsStrength.label",
    description: "BOT.presets.enhanceAbilityBullsStrength.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        abilityCheckAdvantages: ["str"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityCatsGrace",
    label: "BOT.presets.enhanceAbilityCatsGrace.label",
    description: "BOT.presets.enhanceAbilityCatsGrace.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        abilityCheckAdvantages: ["dex"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityBearsEndurance",
    label: "BOT.presets.enhanceAbilityBearsEndurance.label",
    description: "BOT.presets.enhanceAbilityBearsEndurance.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      temporaryHp: {
        formula: "2d6",
        timing: "activation",
        targetMode: "self",
        mode: "keepHighest",
      },
      buffs: {
        abilityCheckAdvantages: ["con"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityEaglesSplendor",
    label: "BOT.presets.enhanceAbilityEaglesSplendor.label",
    description: "BOT.presets.enhanceAbilityEaglesSplendor.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        abilityCheckAdvantages: ["cha"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityFoxsCunning",
    label: "BOT.presets.enhanceAbilityFoxsCunning.label",
    description: "BOT.presets.enhanceAbilityFoxsCunning.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        abilityCheckAdvantages: ["int"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityOwlsWisdom",
    label: "BOT.presets.enhanceAbilityOwlsWisdom.label",
    description: "BOT.presets.enhanceAbilityOwlsWisdom.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        abilityCheckAdvantages: ["wis"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "magicWeapon",
    label: "BOT.presets.magicWeapon.label",
    description: "BOT.presets.magicWeapon.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1",
        targetMode: "triggerTarget",
      },
      buffs: {
        attackBonus: "+1",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "crusadersMantle",
    label: "BOT.presets.crusadersMantle.label",
    description: "BOT.presets.crusadersMantle.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d4",
        type: "radiant",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "flameArrows",
    label: "BOT.presets.flameArrows.label",
    description: "BOT.presets.flameArrows.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "rwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "fire",
        targetMode: "triggerTarget",
      },
      charges: 12,
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "searingSmite",
    label: "BOT.presets.searingSmite.label",
    description: "BOT.presets.searingSmite.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "fire",
        targetMode: "triggerTarget",
      },
      charges: 1,
      consumeOnTrigger: true,
      triggerFrequency: "none",
    },
  },
  {
    id: "banishingSmite",
    label: "BOT.presets.banishingSmite.label",
    description: "BOT.presets.banishingSmite.description",
    flag: {
      targetMode: "self",
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "5d10",
        type: "force",
        targetMode: "triggerTarget",
      },
      charges: 1,
      consumeOnTrigger: true,
      triggerFrequency: "none",
    },
  },
  {
    id: "spiritShroudCold",
    label: "BOT.presets.spiritShroudCold.label",
    description: "BOT.presets.spiritShroud.description",
    flag: {
      targetMode: "self",
      type: "anyAttack",
      condition: "hit",
      damage: {
        formula: "1d8",
        type: "cold",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "spiritShroudRadiant",
    label: "BOT.presets.spiritShroudRadiant.label",
    description: "BOT.presets.spiritShroud.description",
    flag: {
      targetMode: "self",
      type: "anyAttack",
      condition: "hit",
      damage: {
        formula: "1d8",
        type: "radiant",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "spiritShroudNecrotic",
    label: "BOT.presets.spiritShroudNecrotic.label",
    description: "BOT.presets.spiritShroud.description",
    flag: {
      targetMode: "self",
      type: "anyAttack",
      condition: "hit",
      damage: {
        formula: "1d8",
        type: "necrotic",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "elementalWeaponAcid",
    label: "BOT.presets.elementalWeaponAcid.label",
    description: "BOT.presets.elementalWeapon.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d4",
        type: "acid",
        targetMode: "triggerTarget",
      },
      buffs: {
        attackBonus: "+1",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "elementalWeaponCold",
    label: "BOT.presets.elementalWeaponCold.label",
    description: "BOT.presets.elementalWeapon.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d4",
        type: "cold",
        targetMode: "triggerTarget",
      },
      buffs: {
        attackBonus: "+1",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "elementalWeaponFire",
    label: "BOT.presets.elementalWeaponFire.label",
    description: "BOT.presets.elementalWeapon.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d4",
        type: "fire",
        targetMode: "triggerTarget",
      },
      buffs: {
        attackBonus: "+1",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "elementalWeaponLightning",
    label: "BOT.presets.elementalWeaponLightning.label",
    description: "BOT.presets.elementalWeapon.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d4",
        type: "lightning",
        targetMode: "triggerTarget",
      },
      buffs: {
        attackBonus: "+1",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "elementalWeaponThunder",
    label: "BOT.presets.elementalWeaponThunder.label",
    description: "BOT.presets.elementalWeapon.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d4",
        type: "thunder",
        targetMode: "triggerTarget",
      },
      buffs: {
        attackBonus: "+1",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "shield",
    label: "BOT.presets.shield.label",
    description: "BOT.presets.shield.description",
    flag: {
      targetMode: "self",
      type: "passive",
      buffs: {
        ac: 5,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "invisibility",
    label: "BOT.presets.invisibility.label",
    description: "BOT.presets.invisibility.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      status: {
        id: "invisible",
        ids: ["invisible"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "always",
        removeWhenBuffEnds: true,
      },
      endConditions: {
        onAttack: true,
        onSpellCast: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "greaterInvisibility",
    label: "BOT.presets.greaterInvisibility.label",
    description: "BOT.presets.greaterInvisibility.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      status: {
        id: "invisible",
        ids: ["invisible"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "always",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromPoison",
    label: "BOT.presets.protectionFromPoison.label",
    description: "BOT.presets.protectionFromPoison.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["poison"],
        conditionImmunities: ["poisoned"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "blur",
    label: "BOT.presets.blur.label",
    description: "BOT.presets.blur.description",
    flag: {
      targetMode: "self",
      type: "passive",
      buffs: {
        incomingAttackMode: "disadvantage",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEvilAndGood",
    label: "BOT.presets.protectionFromEvilAndGood.label",
    description: "BOT.presets.protectionFromEvilAndGood.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        incomingAttackMode: "disadvantage",
        incomingAttackCreatureTypes: ["aberration", "celestial", "elemental", "fey", "fiend", "undead"],
        conditionImmunities: ["charmed", "frightened"],
      },
      reminders: {
        enabled: true,
        message: "BOT.presets.protectionFromEvilAndGood.reminder",
        timing: {
          turnStart: true,
        },
        visibility: "gm",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "freedomOfMovement",
    label: "BOT.presets.freedomOfMovement.label",
    description: "BOT.presets.freedomOfMovement.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        conditionImmunities: ["restrained", "paralyzed"],
      },
      reminders: {
        enabled: true,
        message: "BOT.presets.freedomOfMovement.reminder",
        timing: {
          turnStart: true,
        },
        visibility: "gm",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "mindBlank",
    label: "BOT.presets.mindBlank.label",
    description: "BOT.presets.mindBlank.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        immunities: ["psychic"],
        conditionImmunities: ["charmed"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "blindness",
    label: "BOT.presets.blindness.label",
    description: "BOT.presets.blindness.description",
    flag: {
      targetMode: "target",
      allowMultipleTargets: true,
      multiTargetLimit: {
        enabled: true,
        baseTargets: 1,
        baseSpellLevel: 2,
        targetsPerLevelAbove: 1,
      },
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "con",
        dcSource: "origin",
        activationApplyOn: "failure",
        repeat: {
          enabled: true,
          timing: "endTurn",
          endsBuffOn: "success",
        },
      },
      status: {
        id: "blinded",
        ids: ["blinded"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "deafness",
    label: "BOT.presets.deafness.label",
    description: "BOT.presets.deafness.description",
    flag: {
      targetMode: "target",
      allowMultipleTargets: true,
      multiTargetLimit: {
        enabled: true,
        baseTargets: 1,
        baseSpellLevel: 2,
        targetsPerLevelAbove: 1,
      },
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "con",
        dcSource: "origin",
        activationApplyOn: "failure",
        repeat: {
          enabled: true,
          timing: "endTurn",
          endsBuffOn: "success",
        },
      },
      status: {
        id: "deafened",
        ids: ["deafened"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "holdPerson",
    label: "BOT.presets.holdPerson.label",
    description: "BOT.presets.holdPerson.description",
    flag: {
      targetMode: "target",
      allowMultipleTargets: true,
      targetFilters: {
        creatureTypes: ["humanoid"],
      },
      multiTargetLimit: {
        enabled: true,
        baseTargets: 1,
        baseSpellLevel: 2,
        targetsPerLevelAbove: 1,
      },
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
        repeat: {
          enabled: true,
          timing: "endTurn",
          endsBuffOn: "success",
        },
      },
      status: {
        id: "paralyzed",
        ids: ["paralyzed"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "holdMonster",
    label: "BOT.presets.holdMonster.label",
    description: "BOT.presets.holdMonster.description",
    flag: {
      targetMode: "target",
      allowMultipleTargets: true,
      targetFilters: {
        excludedCreatureTypes: ["undead"],
      },
      multiTargetLimit: {
        enabled: true,
        baseTargets: 1,
        baseSpellLevel: 5,
        targetsPerLevelAbove: 1,
      },
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
        repeat: {
          enabled: true,
          timing: "endTurn",
          endsBuffOn: "success",
        },
      },
      status: {
        id: "paralyzed",
        ids: ["paralyzed"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "charmPerson",
    label: "BOT.presets.charmPerson.label",
    description: "BOT.presets.charmPerson.description",
    flag: {
      targetMode: "target",
      targetFilters: {
        creatureTypes: ["humanoid"],
      },
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      status: {
        id: "charmed",
        ids: ["charmed"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "animalFriendship",
    label: "BOT.presets.animalFriendship.label",
    description: "BOT.presets.animalFriendship.description",
    flag: {
      targetMode: "target",
      targetFilters: {
        creatureTypes: ["beast"],
        abilityScores: {
          int: { max: 3 },
        },
      },
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      status: {
        id: "charmed",
        ids: ["charmed"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "dominateBeast",
    label: "BOT.presets.dominateBeast.label",
    description: "BOT.presets.dominateBeast.description",
    flag: {
      targetMode: "target",
      targetFilters: {
        creatureTypes: ["beast"],
      },
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
        repeat: {
          enabled: true,
          timing: "endTurn",
          endsBuffOn: "success",
        },
      },
      status: {
        id: "charmed",
        ids: ["charmed"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "dominatePerson",
    label: "BOT.presets.dominatePerson.label",
    description: "BOT.presets.dominatePerson.description",
    flag: {
      targetMode: "target",
      targetFilters: {
        creatureTypes: ["humanoid"],
      },
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
        repeat: {
          enabled: true,
          timing: "endTurn",
          endsBuffOn: "success",
        },
      },
      status: {
        id: "charmed",
        ids: ["charmed"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "charmMonster",
    label: "BOT.presets.charmMonster.label",
    description: "BOT.presets.charmMonster.description",
    flag: {
      targetMode: "target",
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      status: {
        id: "charmed",
        ids: ["charmed"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "faerieFire",
    label: "BOT.presets.faerieFire.label",
    description: "BOT.presets.faerieFire.description",
    flag: {
      targetMode: "target",
      allowMultipleTargets: true,
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "dex",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      buffs: {
        incomingAttackMode: "advantage",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "tashasHideousLaughter",
    label: "BOT.presets.tashasHideousLaughter.label",
    description: "BOT.presets.tashasHideousLaughter.description",
    flag: {
      targetMode: "target",
      targetFilters: {
        abilityScores: {
          int: { min: 5 },
        },
      },
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
        repeat: {
          enabled: true,
          timing: "endTurn",
          endsBuffOn: "success",
          onDamaged: true,
        },
      },
      status: {
        id: "incapacitated",
        ids: ["incapacitated", "prone"],
        timing: "activation",
        targetMode: "self",
        applyCondition: "saveFailure",
        removeWhenBuffEnds: true,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "slow",
    label: "BOT.presets.slow.label",
    description: "BOT.presets.slow.description",
    flag: {
      targetMode: "target",
      allowMultipleTargets: true,
      multiTargetLimit: {
        enabled: true,
        baseTargets: 6,
        baseSpellLevel: 3,
        targetsPerLevelAbove: 0,
      },
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
        repeat: {
          enabled: true,
          timing: "endTurn",
          endsBuffOn: "success",
        },
      },
      buffs: {
        ac: -2,
        savingThrowModifiers: {
          dex: "-2",
        },
        movement: { enabled: true, mode: "multiply", value: "0.5", types: ["all"] },
      },
      reminders: {
        enabled: true,
        message: "BOT.presets.slow.reminder",
        timing: {
          turnStart: true,
        },
        visibility: "gm",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "bestowCurseStr",
    label: "BOT.presets.bestowCurseStr.label",
    description: "BOT.presets.bestowCurseStr.description",
    flag: {
      targetMode: "target",
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      buffs: {
        abilityCheckDisadvantages: ["str"],
        savingThrowDisadvantages: ["str"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "bestowCurseDex",
    label: "BOT.presets.bestowCurseDex.label",
    description: "BOT.presets.bestowCurseDex.description",
    flag: {
      targetMode: "target",
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      buffs: {
        abilityCheckDisadvantages: ["dex"],
        savingThrowDisadvantages: ["dex"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "bestowCurseCon",
    label: "BOT.presets.bestowCurseCon.label",
    description: "BOT.presets.bestowCurseCon.description",
    flag: {
      targetMode: "target",
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      buffs: {
        abilityCheckDisadvantages: ["con"],
        savingThrowDisadvantages: ["con"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "bestowCurseInt",
    label: "BOT.presets.bestowCurseInt.label",
    description: "BOT.presets.bestowCurseInt.description",
    flag: {
      targetMode: "target",
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      buffs: {
        abilityCheckDisadvantages: ["int"],
        savingThrowDisadvantages: ["int"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "bestowCurseWis",
    label: "BOT.presets.bestowCurseWis.label",
    description: "BOT.presets.bestowCurseWis.description",
    flag: {
      targetMode: "target",
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      buffs: {
        abilityCheckDisadvantages: ["wis"],
        savingThrowDisadvantages: ["wis"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "bestowCurseCha",
    label: "BOT.presets.bestowCurseCha.label",
    description: "BOT.presets.bestowCurseCha.description",
    flag: {
      targetMode: "target",
      type: "passive",
      save: {
        enabled: true,
        timing: "activation",
        ability: "wis",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      buffs: {
        abilityCheckDisadvantages: ["cha"],
        savingThrowDisadvantages: ["cha"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
];
