export const BUFF_PRESETS = [
  {
    id: "bless",
    label: "BOT.presets.bless.label",
    description: "BOT.presets.bless.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      rollModifier: {
        enabled: true,
        formula: "1d4",
        rollTypes: ["attack", "save"],
      },
      consumeOnTrigger: false,
    },
  },
  {
    id: "bane",
    label: "BOT.presets.bane.label",
    description: "BOT.presets.bane.description",
    flag: {
      targetMode: "target",
      type: "passive",
      rollModifier: {
        enabled: true,
        formula: "-1d4",
        rollTypes: ["attack", "save"],
      },
      save: {
        enabled: true,
        timing: "activation",
        ability: "cha",
        dcSource: "origin",
        activationApplyOn: "failure",
      },
      consumeOnTrigger: false,
    },
  },
  {
    id: "guidance",
    label: "BOT.presets.guidance.label",
    description: "BOT.presets.guidance.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      rollModifier: {
        enabled: true,
        formula: "1d4",
        rollTypes: ["ability", "skill"],
      },
      charges: 1,
      consumeOnTrigger: false,
    },
  },
  {
    id: "resistance",
    label: "BOT.presets.resistance.label",
    description: "BOT.presets.resistance.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      rollModifier: {
        enabled: true,
        formula: "1d4",
        rollTypes: ["save"],
      },
      charges: 1,
      consumeOnTrigger: false,
    },
  },
  {
    id: "hex",
    label: "BOT.presets.hex.label",
    description: "BOT.presets.hex.description",
    flag: {
      targetMode: "self",
      rememberTargetOnActivation: true,
      requireStoredTargetMatch: true,
      type: "anyAttack",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "necrotic",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
    },
  },
  {
    id: "huntersMark",
    label: "BOT.presets.huntersMark.label",
    description: "BOT.presets.huntersMark.description",
    flag: {
      targetMode: "self",
      rememberTargetOnActivation: true,
      requireStoredTargetMatch: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d6",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
    },
  },
  {
    id: "fireShieldWarm",
    label: "BOT.presets.fireShieldWarm.label",
    description: "BOT.presets.fireShieldWarm.description",
    flag: {
      targetMode: "self",
      type: "damaged",
      receivedAttackType: "melee",
      damage: {
        formula: "2d8",
        type: "fire",
        targetMode: "attacker",
      },
      buffs: {
        resistances: ["cold"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "fireShieldChill",
    label: "BOT.presets.fireShieldChill.label",
    description: "BOT.presets.fireShieldChill.description",
    flag: {
      targetMode: "self",
      type: "damaged",
      receivedAttackType: "melee",
      damage: {
        formula: "2d8",
        type: "cold",
        targetMode: "attacker",
      },
      buffs: {
        resistances: ["fire"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "heroism",
    label: "BOT.presets.heroism.label",
    description: "BOT.presets.heroism.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "turnStart",
      temporaryHp: {
        formula: "@origin.spell.mod",
        targetMode: "self",
        mode: "keepHighest",
      },
      buffs: {
        conditionImmunities: ["frightened"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "armorOfAgathys",
    label: "BOT.presets.armorOfAgathys.label",
    description: "BOT.presets.armorOfAgathys.description",
    flag: {
      targetMode: "self",
      type: "damaged",
      receivedAttackType: "melee",
      requireBearerTemporaryHp: true,
      temporaryHp: {
        formula: "@spellLevel * 5",
        timing: "activation",
        targetMode: "self",
        mode: "keepHighest",
      },
      damage: {
        formula: "@spellLevel * 5",
        type: "cold",
        targetMode: "attacker",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "divineFavor",
    label: "BOT.presets.divineFavor.label",
    description: "BOT.presets.divineFavor.description",
    flag: {
      targetMode: "self",
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d4",
        type: "radiant",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "wrathfulSmite",
    label: "BOT.presets.wrathfulSmite.label",
    description: "BOT.presets.wrathfulSmite.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "psychic",
        targetMode: "triggerTarget",
      },
      save: {
        enabled: true,
        timing: "trigger",
        ability: "wis",
        dcSource: "origin",
        effect: "full",
      },
      status: {
        id: "frightened",
        targetMode: "triggerTarget",
        applyCondition: "saveFailure",
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "shieldOfFaith",
    label: "BOT.presets.shieldOfFaith.label",
    description: "BOT.presets.shieldOfFaith.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        ac: 2,
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "brandingSmite",
    label: "BOT.presets.brandingSmite.label",
    description: "BOT.presets.brandingSmite.description",
    flag: {
      targetMode: "self",
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "2d6",
        type: "radiant",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "blindingSmite",
    label: "BOT.presets.blindingSmite.label",
    description: "BOT.presets.blindingSmite.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "3d8",
        type: "radiant",
        targetMode: "triggerTarget",
      },
      save: {
        enabled: true,
        timing: "trigger",
        ability: "con",
        dcSource: "origin",
        effect: "full",
      },
      status: {
        id: "blinded",
        targetMode: "triggerTarget",
        applyCondition: "saveFailure",
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "thunderousSmite",
    label: "BOT.presets.thunderousSmite.label",
    description: "BOT.presets.thunderousSmite.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "2d6",
        type: "thunder",
        targetMode: "triggerTarget",
      },
      save: {
        enabled: true,
        timing: "trigger",
        ability: "str",
        dcSource: "origin",
        effect: "full",
      },
      status: {
        id: "prone",
        targetMode: "triggerTarget",
        applyCondition: "saveFailure",
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "holyWeapon",
    label: "BOT.presets.holyWeapon.label",
    description: "BOT.presets.holyWeapon.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "2d8",
        type: "radiant",
        targetMode: "triggerTarget",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "stoneskin",
    label: "BOT.presets.stoneskin.label",
    description: "BOT.presets.stoneskin.description",
    flag: {
      targetMode: "target",
      type: "passive",
      buffs: {
        resistances: ["bludgeoning", "piercing", "slashing"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enlarge",
    label: "BOT.presets.enlarge.label",
    description: "BOT.presets.enlarge.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "weaponAttack",
      condition: "hit",
      damage: {
        formula: "1d4",
        targetMode: "triggerTarget",
      },
      buffs: {
        abilityCheckAdvantages: ["str"],
        savingThrowAdvantages: ["str"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "absorbElementsAcid",
    label: "BOT.presets.absorbElementsAcid.label",
    description: "BOT.presets.absorbElements.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "acid",
        targetMode: "triggerTarget",
      },
      buffs: {
        resistances: ["acid"],
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "absorbElementsCold",
    label: "BOT.presets.absorbElementsCold.label",
    description: "BOT.presets.absorbElements.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "cold",
        targetMode: "triggerTarget",
      },
      buffs: {
        resistances: ["cold"],
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "absorbElementsFire",
    label: "BOT.presets.absorbElementsFire.label",
    description: "BOT.presets.absorbElements.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "fire",
        targetMode: "triggerTarget",
      },
      buffs: {
        resistances: ["fire"],
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "absorbElementsLightning",
    label: "BOT.presets.absorbElementsLightning.label",
    description: "BOT.presets.absorbElements.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "lightning",
        targetMode: "triggerTarget",
      },
      buffs: {
        resistances: ["lightning"],
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "absorbElementsThunder",
    label: "BOT.presets.absorbElementsThunder.label",
    description: "BOT.presets.absorbElements.description",
    flag: {
      targetMode: "self",
      type: "mwak",
      condition: "hit",
      damage: {
        formula: "1d6",
        type: "thunder",
        targetMode: "triggerTarget",
      },
      buffs: {
        resistances: ["thunder"],
      },
      consumeOnTrigger: true,
      charges: 1,
      triggerFrequency: "none",
    },
  },
  {
    id: "haste",
    label: "BOT.presets.haste.label",
    description: "BOT.presets.haste.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        ac: 2,
        savingThrowAdvantages: ["dex"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "falseLife",
    label: "BOT.presets.falseLife.label",
    description: "BOT.presets.falseLife.description",
    flag: {
      targetMode: "self",
      type: "passive",
      temporaryHp: {
        formula: "1d4 + 4 + ((@spellLevel - 1) * 5)",
        timing: "activation",
        targetMode: "self",
        mode: "keepHighest",
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEnergyAcid",
    label: "BOT.presets.protectionFromEnergyAcid.label",
    description: "BOT.presets.protectionFromEnergy.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["acid"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEnergyCold",
    label: "BOT.presets.protectionFromEnergyCold.label",
    description: "BOT.presets.protectionFromEnergy.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["cold"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEnergyFire",
    label: "BOT.presets.protectionFromEnergyFire.label",
    description: "BOT.presets.protectionFromEnergy.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["fire"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEnergyLightning",
    label: "BOT.presets.protectionFromEnergyLightning.label",
    description: "BOT.presets.protectionFromEnergy.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["lightning"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "protectionFromEnergyThunder",
    label: "BOT.presets.protectionFromEnergyThunder.label",
    description: "BOT.presets.protectionFromEnergy.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        resistances: ["thunder"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityBullsStrength",
    label: "BOT.presets.enhanceAbilityBullsStrength.label",
    description: "BOT.presets.enhanceAbilityBullsStrength.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        abilityCheckAdvantages: ["str"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityCatsGrace",
    label: "BOT.presets.enhanceAbilityCatsGrace.label",
    description: "BOT.presets.enhanceAbilityCatsGrace.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        abilityCheckAdvantages: ["dex"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityBearsEndurance",
    label: "BOT.presets.enhanceAbilityBearsEndurance.label",
    description: "BOT.presets.enhanceAbilityBearsEndurance.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      temporaryHp: {
        formula: "2d6",
        timing: "activation",
        targetMode: "self",
        mode: "keepHighest",
      },
      buffs: {
        abilityCheckAdvantages: ["con"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityEaglesSplendor",
    label: "BOT.presets.enhanceAbilityEaglesSplendor.label",
    description: "BOT.presets.enhanceAbilityEaglesSplendor.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        abilityCheckAdvantages: ["cha"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityFoxsCunning",
    label: "BOT.presets.enhanceAbilityFoxsCunning.label",
    description: "BOT.presets.enhanceAbilityFoxsCunning.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        abilityCheckAdvantages: ["int"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
  {
    id: "enhanceAbilityOwlsWisdom",
    label: "BOT.presets.enhanceAbilityOwlsWisdom.label",
    description: "BOT.presets.enhanceAbilityOwlsWisdom.description",
    flag: {
      targetMode: "target",
      fallbackToSelfIfNoTarget: true,
      type: "passive",
      buffs: {
        abilityCheckAdvantages: ["wis"],
      },
      consumeOnTrigger: false,
      triggerFrequency: "none",
    },
  },
];
